### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by Urobi96** [IMB11-Mods/SkinShuffle#104]
### Describe the issue

When I click on "skin presets" the Minecraft is crashing, I left only Fabric apy and skin shuffle 2.1.0. Also I tried using Skin Shuffle other version 2.0.4 and it's still crash

### SkinShuffle version

2.1.0, 2.0.4

### Extra information

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1011.method_4307()" because "this.field_5200" is null

**Comment by IMB11** [comment]
Duplicate of #102

**Comment by ZKL5859** [comment]
i have the same issue but my game crashes when i click it, i use not enough crashes and when i click it again it doesn't crash
