### ISSUE TITLE
Что-то сломалось

### ISSUE THREAD

**Issue by retyka124** [IMB11-Mods/SkinShuffle#110]
### Describe the issue

запускаю игру с этим модом игра не запускается удаляю всё работает мод от которого зависит скачен скачивал с других сайтов со ровно не работает

### SkinShuffle version

1.20.6

**Comment by IMB11** [comment]
Загрузите файл «latest.log» на сайт https://mclo.gs/.

**Comment by retyka124** [comment]
у меня нету файла latest.log

**Comment by retyka124** [comment]
сделал ту две ошибки

**Comment by IMB11** [comment]
Please upload your `latest.log` file to https://mclo.gs/ - you can find it in `.minecraft/logs`

**Comment by retyka124** [comment]
загрузил

**Comment by IMB11** [comment]
Please post the link here.

**Comment by retyka124** [comment]
как?

**Comment by IMB11** [comment]
Copy the URL from your browser's URL bar when you have the mclo.gs website open after you have uploaded your logs.

**Comment by retyka124** [comment]
https://mclo.gs/xSFS3JZ

**Comment by IMB11** [comment]
Hi, really sorry, but SkinShuffle only works if you actually own an account for Minecraft - yes I know it must be difficult to buy an account within Russia at the moment but there's nothing I can really do here.
