### ISSUE TITLE
Bug with FancyMenu

### ISSUE THREAD

**Issue by Techduk** [IMB11-Mods/SkinShuffle#111]
### Describe the issue

Mod little won't support background images from FancyMenu...
Better watch video:

### SkinShuffle version

2.0.4+1.21

### Extra information

https://github.com/user-attachments/assets/d04b6758-6173-48c3-9d73-6434f319bd39

**Comment by IMB11** [comment]
The SkinShuffle menu is not designed to be modified using FancyMenu.
