### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by seriousfreezing** [IMB11-Mods/SkinShuffle#113]
### Describe the issue

[crash-2024-09-04_18.54.41-client.txt](https://github.com/user-attachments/files/16881751/crash-2024-09-04_18.54.41-client.txt)
[crash-2024-09-04_19.28.51-client.txt](https://github.com/user-attachments/files/16881752/crash-2024-09-04_19.28.51-client.txt)
[crash-2024-09-04_19.30.11-client.txt](https://github.com/user-attachments/files/16881753/crash-2024-09-04_19.30.11-client.txt)

### SkinShuffle version

2.2.2+1.21

**Comment by IMB11** [comment]
Delete your `.minecraft/config/skinshuffle` folder

**Comment by seriousfreezing** [comment]
I've done this before, do I have to do it every crash?

**Comment by EngurRuzgar** [comment]
https://tryitands.ee/

**Comment by seriousfreezing** [comment]
This gif doesn't even make sense, I've already deleted the skinshuffle config folder, but after a while it crashes again! That's not even a temporary fix

**Comment by IMB11** [comment]
Im working on a permanent fix, this is a workaround for now.
