### ISSUE TITLE
Closes on startup, with a saving world text?

### ISSUE THREAD

**Issue by VenomousReaperGoat** [IMB11-Mods/SkinShuffle#14]
### Describe the issue

Ive been using this mod for a week now, and it worked flawlessly. Suddenly after i quit a multiplayer world, my game crashed and when going back in it instantly closes with a saving world text. I have not done anything to the settings of the game. Game works without the mod.

Opening on a new instance started working again, But same results, crashes after a few uses.

### Relevant log output

https://mclo.gs/Ep52dJQ

**Comment by enjarai** [comment]
Another mod called "cheatutils" is making an incorrect assumption when modifying player rendering, causing a conflict with this one. Remove either mod, or ask their side to add a nullcheck for `client.player`.

**Comment by mineblock11** [comment]
https://www.curseforge.com/minecraft/mc-mods/cheatutils-by-zergatul

We do not support clients, cheats, or modifications that allow you to access the game without paying for it or give you an unfair competitive advantage.
