### ISSUE TITLE
Support alternative APIs

### ISSUE THREAD

**Issue by ItsukaHiro** [IMB11-Mods/SkinShuffle#25]
### Describe the issue

The issue is when I change the skin with SkinShuffle in a server:

- Mod: "You're using the new one."
- My friend in server: "You're using the new one."
- NameMC: "You're using the new one."
- Me in FOV: I'm using the old one.

The is no log in console. My server is Paper (using SkinRestorer).

Note: Everything seem work fine when i'm using old version (0.1 and 0.1.1)

**Comment by mineblock11** [comment]
Could you please provide footage, logs, mc version and mod version please?

PS @enjarai we should probably add that to the issue template

**Comment by enjarai** [comment]
> Could you please provide footage, logs, mc version and mod version please?
> 
> PS @enjarai we should probably add that to the issue template

It already asks for logs, but mc version and mod version are a good idea.

**Comment by ItsukaHiro** [comment]
> Could you please provide footage, logs, mc version and mod version please?
> 
> PS @enjarai we should probably add that to the issue template

[Sample Video](https://github.com/ItsukaHiro/Just-a-place-to-push-some-file/blob/main/rs.mp4).

I also check the console, both server & client-side. There is nothing.

Btw, I can confirm NameMC update my skin to the new one, and my friend in server can see my new skin. I'm the only one still see the old one.

**Comment by ItsukaHiro** [comment]
I forgot: 
![image](https://github.com/mineblock11/SkinShuffle/assets/64533662/99294ac0-e9dc-41cd-a218-9a583a707de6)

This is the list of mods I'm using. I can confirm nothing in them (except SkinShuffle) can change the skin client-side.

**Comment by mineblock11** [comment]
I believe skinrestorer doesn't use Mojang's skin API, we can likely update skins for other APIs as well in 0.4.0

**Comment by ItsukaHiro** [comment]
Actually... As I remember, old version of SkinShuffle still work without any problem (in the same server). I'll try old version for more details.

But, as I mention: I'm the only one see the old skin. My friend (doesn't have SkinShuffle) can still see my new skin.

I even check my profile on NameMC, and they actually update my skin to new one.

**Comment by IMB11** [comment]
Will never be done, alternative skin APIs are used for piracy too much.
