### ISSUE TITLE
Add ely.by support if it is not already there

### ISSUE THREAD

**Issue by Wayturns** [IMB11-Mods/SkinShuffle#42]
### Describe your suggestion

As title says it'd be amazing to have ely.by skin system.
Also if my friends which have cracked mc install the mod will their game crash or will the mod just not work?

**Comment by mineblock11** [comment]
The mod will work, and other player's capes will be visible. But they wont have capes

**Comment by IMB11** [comment]
We will not be supporting alternative skin APIs, see #25
