### ISSUE TITLE
(1.20) Crashing on title screen

### ISSUE THREAD

**Issue by WisteriaSp** [IMB11-Mods/SkinShuffle#51]
### Describe the issue

The game crashes whenever the title screen tries to load. Weirdly enough it seems like it doesn't crash if the user has zero presets.

### Relevant log output

https://mclo.gs/9SR44ox - Latest.log

### SkinShuffle version

1.0.1+1.20 on Quilt Loader

### Extra information

https://mclo.gs/WLYCHGQ - Crash report

**Comment by mineblock11** [comment]
SkinShuffle isn't marked compatible to use on quilt for a reason.

**Comment by WisteriaSp** [comment]
it crashes on fabric too lol https://mclo.gs/5evOTBF - crash report
https://mclo.gs/70pHgc2 - latest.log

**Comment by IMB11** [comment]
This is a crash caused by Fabrication.
![image](https://github.com/IMB11/SkinShuffle/assets/93472213/2e969388-0ede-47ef-9b4d-29f1d6d9f6fe)
