### ISSUE TITLE
failed authentication

### ISSUE THREAD

**Issue by MedJb** [IMB11-Mods/SkinShuffle#90]
### Describe the issue

I used Ely.by authentication URL, the skin shows but i still got message (you are not authenticated...) but the problem raise when i use replay mod cz my skin dosen't show in replays. I tried to download and put it manually (.png file) but the problem presist.

### SkinShuffle version

SkinShuffle-2.0.4+1.21

**Comment by IMB11** [comment]
SkinShuffle does not support piracy. Go and buy the game like everyone else.
