### ISSUE TITLE
Skin Shuffle crashes with Remove Reloading Screen

### ISSUE THREAD

**Issue by Mizuuta** [IMB11-Mods/SkinShuffle#91]
### Describe the issue

Minecraft crashes when loading the main menu if Remove Reloading Screen (5.0.2+mc1.21-fabric) and Skin Shuffle (2.0.4+1.21) are installed.

### Relevant log output

https://mclo.gs/hJmaji4

### SkinShuffle version

2.0.4+1.21

**Comment by IMB11** [comment]
Please report this to remove reloading screen, this is expected if they're doing hacky things like removing a loading screen which has a purpose.
