### ISSUE TITLE
Crash if you go to the main menu from the "Welcome to Minecraft" screen.

### ISSUE THREAD

**Issue by Mizuuta** [IMB11-Mods/SkinShuffle#92]
### Describe the issue

Minecraft crashes if you (ex. start a fresh instance) and are greeted with the "Welcome to Minecraft" screen and then press on "Continue" the game crashes.

### Relevant log output

https://mclo.gs/e3uFnIA

### SkinShuffle version

2.0.4+1.21

**Comment by IMB11** [comment]
Will investigate.

**Comment by morgantic** [comment]
Same thing happens when you directly launch an instance with multi MC into a server, and then go into the ESC Menu, it crashes.

**Comment by IMB11** [comment]
Might be fixed in the next update. let me know if it isn't :+1:

**Comment by morgantic** [comment]
I'm confused by the history. Is this now not planned, fixed, or closed without action? :D
